# Generated by Django 5.2.7 on 2025-10-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="passenger_age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="age_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("U", "Universal"),
                    ("U/A 13+", "Under Adult Supervision (13+)"),
                    ("U/A 16+", "Under Adult Supervision (16+)"),
                    ("A", "Adults only (18+)"),
                ],
                default="U",
                max_length=10,
            ),
        ),
    ]
