# Generated by Django 5.2.7 on 2025-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_passenger_age_booking_passenger_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("U", "Universal (U)"),
                    ("U/A 13+", "Under Adult Supervision (13+)"),
                    ("U/A 16+", "Under Adult Supervision (16+)"),
                    ("A", "Adults only (18+)"),
                ],
                default="U",
                max_length=10,
            ),
        ),
    ]
